config/routes.rb
PostAssignment::Application.routes.draw do
  resources :posts do
    member do
      get "myshowdata"
      get "myedit"
      get "mydelete"
      put "myupdate"
      post "create_comment"
      delete "delete_comment"
    end

    collection do
      get "index"
      get "myform"
      post "mycreate"
      get "mydatalist"

    end
  end

  root :to => 'Posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :description, :title

  validates :title, :presence => true
  validates :description, :presence => true

 has_many :posts_comments



  def self.create_new_entry(parameters)
    a = Post.new(:title => parameters['title'],:description => parameters['description'])
    a.save
    return a
  end
end

app/models/posts_comment.rb
class PostsComment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :comment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def myform
    @post = Post.new

    respond_to do |format|
      format.html # myform.html.erb
      format.json { render :json => @post }
    end

  end

  def mycreate
    @post = Post.create_new_entry(params[:post])
    respond_to do |format|
      if @post.save
        format.html { redirect_to mydatalist_posts_path, :notice => 'Data was successfully created.' }
      else
        format.html { render :action => "myform" }
      end
    end
  end

  def create_comment
    #@post = Post.find(params[:id])
    #@comment = @post.posts_comments.new(params[:posts_comment])
    # if @comment.save
    # redirect_to myshowdata_post_path, :notice => 'Comment was successfully created.'
    #end
    @post = Post.find(params[:id])


    @new_comment = @post.posts_comments.new(params[:posts_comment])
    @new_comment.save
    @comments = @post.posts_comments
    logger.info @comments.inspect
    respond_to do |format|
      format.js
    end



  end

  def myshowdata
    @post = Post.find(params[:id])
    @comments = @post.posts_comments
    @comment = @post.posts_comments.new
    respond_to do |format|
      format.html # myshowdata.html.erb
    end
  end

  def mydatalist
    @post =  Post.paginate(:page => params[:page], :per_page => 10)
  end

  def myedit
    @post = Post.find(params[:id])
  end

  def mydelete
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to myshowdata_post_path }
    end
  end

  def delete_comment
    @comment = PostsComment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to myshowdata_post_path }
    end
  end


  def myupdate
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to mydatalist_posts_path, :notice => 'Post was successfully updated.' }
      else
        format.html { render :action => "myedit" }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PostAssignment</title>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_comment_form.html.erb
<p>
  <b>Comments:</b>
  <% @comments.each do |comment| %>
      <%#=	 comment.inspect %>
    <p><%= comment.comment %></p>
<%end %>
</p>

app/views/posts/create_comment.js.erb
$("#showcomments").html("<%= escape_javascript(render "comment_form") %>")

app/views/posts/index.html.erb
<h3>To get the form click on the link below</h3>
<%= link_to "My Blog", mydatalist_posts_path %>

app/views/posts/mydatalist.html.erb
<p id="notice"><%= notice %></p>
<h1>List of all data:</h1>

<table border="1">
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>

  <% @post.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= link_to 'Show',myshowdata_post_path(post) %></td>
        <td><%= link_to 'Edit', myedit_post_path(post) %></td>
        <td><%= link_to 'Delete', mydelete_post_path(post), :data => { :confirm => 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<br />
<%= will_paginate @post %>
 <br />
<%= link_to 'Add data', myform_posts_path %>

app/views/posts/myedit.html.erb
<h3>Please Enter the details</h3>

<%= form_for(@post,:url=> myupdate_post_path) do |f| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description %>  <br/>
    </div> <br />

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/posts/myform.html.erb
<h3>Please Enter the details</h3>

<%= form_for(@post,:url=> mycreate_posts_path) do |f| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
          <h4><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h4>

          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description %>  <br/>
    </div> <br />

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/posts/myshowdata.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Description:</b>
  <%= @post.title %>
</p>

<div id="showcomments"> <%= render :partial => "comment_form" %> </div>

<%= form_for @comment,:url=> create_comment_post_path ,:method => "post",:remote => true  do |f| %>
    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment,:id=>"new_comment" %>  <br/>
    </div> <br />

    <div class="actions">
      <%= f.submit :id=>"add_comment" %>
      <!-- <%#= button_tag "  Add Comment  ", :id => "add_comment", :onclick=>"javascript:submitForm()" %> -->

    </div>
<% end %>

<%=	 link_to "Back" ,mydatalist_posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Description:</b>
  <%= @post.description %>
</p>